# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

ENDPOINT = "http://ec2-3-82-188-235.compute-1.amazonaws.com:8080/"

class TestTCDangKy001():
  def setup_method(self, method):
    options = Options()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Chrome(options=options)
    self.driver.maximize_window()
    self.wait = WebDriverWait(self.driver, timeout=10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tCDangKy001(self):
    self.driver.get(ENDPOINT)
    self.driver.set_window_size(974, 1032)
    self.driver.implicitly_wait(3)
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("nguyenhungkhang123@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.NAME, "confirm_password").click()
    self.driver.find_element(By.NAME, "confirm_password").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.wait.until(lambda d: d.find_element(By.CSS_SELECTOR, "input:nth-child(3)"))
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("nguyenhungkhang123@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.implicitly_wait(30)
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(3) img").click()

class TestTCDangKy002():
  def setup_method(self, method):
    options = Options()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Chrome(options=options)
    self.driver.maximize_window()
    self.wait = WebDriverWait(self.driver, timeout=10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def test_tCDangKy002(self):
    self.driver.get(ENDPOINT)
    self.driver.set_window_size(974, 1032)
    self.driver.implicitly_wait(3)
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("nguyenhungkhang123@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.NAME, "confirm_password").click()
    self.driver.find_element(By.NAME, "confirm_password").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(10.0)
    self.driver.find_element(By.NAME, "confirm_password").click()

class TestTCDangKy003():
  def setup_method(self, method):
    options = Options()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Chrome(options=options)
    self.driver.maximize_window()
    self.wait = WebDriverWait(self.driver, timeout=10)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_tCDangKy002(self):
    self.driver.get(ENDPOINT)
    self.driver.set_window_size(974, 1032)
    self.driver.implicitly_wait(3)
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("123@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.NAME, "confirm_password").click()
    self.driver.find_element(By.NAME, "confirm_password").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(10.0)
    self.driver.find_element(By.NAME, "confirm_password").click()
  
class TestTCDangKy004():
  def setup_method(self, method):
    options = Options()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Chrome(options=options)
    self.driver.maximize_window()
    self.wait = WebDriverWait(self.driver, timeout=10)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_tCDangKy002(self):
    self.driver.get(ENDPOINT)
    self.driver.set_window_size(974, 1032)
    self.driver.implicitly_wait(3)
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("nguyenhungkhang456@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.NAME, "confirm_password").click()
    self.driver.find_element(By.NAME, "confirm_password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(10.0)
    self.driver.find_element(By.NAME, "confirm_password").click()

class TestTCDangKy005():
  def setup_method(self, method):
    options = Options()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Chrome(options=options)
    self.driver.maximize_window()
    self.wait = WebDriverWait(self.driver, timeout=10)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_tCDangKy002(self):
    self.driver.get(ENDPOINT)
    self.driver.set_window_size(974, 1032)
    self.driver.implicitly_wait(3)
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("nguyenhungkhang456@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.NAME, "confirm_password").click()
    self.driver.find_element(By.NAME, "confirm_password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(10.0)
    self.driver.find_element(By.NAME, "confirm_password").click()
