# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options
import connection

ENDPOINT = "http://ec2-54-90-106-213.compute-1.amazonaws.com:8080/"
  
def test_tCThongKe001():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("admin@admin.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("1")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) img").click()
  driver.find_element(By.CSS_SELECTOR, "input").click()

  driver.quit()
  
def test_tCThongKe002():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("admin@admin.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("1")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) img").click()
  driver.find_element(By.CSS_SELECTOR, "input").click()
  driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > canvas").click()

  driver.quit()

  
def test_tCThongKe003():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("admin@admin.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("1")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) img").click()
  driver.find_element(By.CSS_SELECTOR, "input").click()
  driver.find_element(By.CSS_SELECTOR, "input").send_keys("0%")
  driver.find_element(By.CSS_SELECTOR, ".form-input").click()
  driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .content-start").click()
  driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > canvas").click()

  driver.quit()

  
def test_tCThongKe004():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("admin@admin.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("1")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) img").click()
  driver.find_element(By.CSS_SELECTOR, "input").click()
  driver.find_element(By.CSS_SELECTOR, "input").send_keys("CBGP")
  driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(1)").click()
  driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > canvas").click()

  driver.quit()

  
def test_tCThongKe005():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  ait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("admin@admin.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("1")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) img").click()
  driver.find_element(By.CSS_SELECTOR, "input").click()
  driver.find_element(By.CSS_SELECTOR, "input").send_keys("CBGP")
  driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(1)").click()
  driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > canvas").click()
  driver.find_element(By.CSS_SELECTOR, "table:nth-child(2) tr:nth-child(1) > td:nth-child(4) > p").click()

  driver.quit()
