# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options
import connection

ENDPOINT = "http://ec2-54-90-106-213.compute-1.amazonaws.com:8080/"
  
def test_tCDangNhap001():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("nguyenhungkhang100@gmail.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("123")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  time.sleep(10.0)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()

  driver.quit()

def test_tCDangNhap002():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("nguyenhungkhang123@gmail.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("321")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  time.sleep(10.0)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()

  driver.quit()
  
def test_tCDangNhap003():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("nguyenhungkhang123@gmail.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("123")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  driver.implicitly_wait(30)
  driver.find_element(By.CSS_SELECTOR, ".item:nth-child(3) img").click()

  driver.quit()
  
def test_tCDangNhap004():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("admin@admin.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("123")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  time.sleep(10.0)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()

  driver.quit()

  
def test_tCDangNhap005():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.find_element(By.LINK_TEXT, "Login").click()
  driver.implicitly_wait(3)
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("admin@admin.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("1")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  driver.implicitly_wait(30)
  driver.find_element(By.CSS_SELECTOR, ".item:nth-child(3) img").click()

  driver.quit()
