# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options
import connection

ENDPOINT = "http://ec2-54-90-106-213.compute-1.amazonaws.com:8080/"


  
def test_tCDangKy001():
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.implicitly_wait(3)
  driver.find_element(By.LINK_TEXT, "Sign up").click()
  driver.find_element(By.NAME, "email").click()
  driver.find_element(By.NAME, "email").send_keys("nguyenhungkhang123@gmail.com")
  driver.find_element(By.NAME, "password").click()
  driver.find_element(By.NAME, "password").send_keys("123")
  driver.find_element(By.NAME, "confirm_password").click()
  driver.find_element(By.NAME, "confirm_password").send_keys("123")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  wait.until(lambda d: d.find_element(By.CSS_SELECTOR, "input:nth-child(3)"))
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("nguyenhungkhang123@gmail.com")
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
  driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("123")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  driver.implicitly_wait(30)
  driver.find_element(By.CSS_SELECTOR, ".item:nth-child(3) img").click()

  driver.quit()


def test_tCDangKy002(self):
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)
  vars = {}

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.implicitly_wait(3)
  driver.find_element(By.LINK_TEXT, "Sign up").click()
  driver.find_element(By.NAME, "email").click()
  driver.find_element(By.NAME, "email").send_keys("nguyenhungkhang123@gmail.com")
  driver.find_element(By.NAME, "password").click()
  driver.find_element(By.NAME, "password").send_keys("123")
  driver.find_element(By.NAME, "confirm_password").click()
  driver.find_element(By.NAME, "confirm_password").send_keys("123")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  time.sleep(10.0)
  driver.find_element(By.NAME, "confirm_password").click()

  driver.quit()

def test_tCDangKy003(self):
  driver = connection.test_connection_driver()
  driver.maximize_window()
  wait = WebDriverWait(driver, timeout=10)
  vars = {}

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.implicitly_wait(3)
  driver.find_element(By.LINK_TEXT, "Sign up").click()
  driver.find_element(By.NAME, "email").click()
  driver.find_element(By.NAME, "email").send_keys("123@gmail.com")
  driver.find_element(By.NAME, "password").click()
  driver.find_element(By.NAME, "password").send_keys("123")
  driver.find_element(By.NAME, "confirm_password").click()
  driver.find_element(By.NAME, "confirm_password").send_keys("123")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  time.sleep(10.0)
  driver.find_element(By.NAME, "confirm_password").click()

  driver.quit()
  

def test_tCDangKy004(self):

  driver = connection.test_connection_driver()
  wait = WebDriverWait(driver, timeout=10)
  vars = {}

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.implicitly_wait(3)
  driver.find_element(By.LINK_TEXT, "Sign up").click()
  driver.find_element(By.NAME, "email").click()
  driver.find_element(By.NAME, "email").send_keys("nguyenhungkhang456@gmail.com")
  driver.find_element(By.NAME, "password").click()
  driver.find_element(By.NAME, "password").send_keys("123")
  driver.find_element(By.NAME, "confirm_password").click()
  driver.find_element(By.NAME, "confirm_password").send_keys("1234")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  time.sleep(10.0)
  driver.find_element(By.NAME, "confirm_password").click()

  driver.quit()



def test_tCDangKy005(self):
  driver = connection.test_connection_driver()
  wait = WebDriverWait(driver, timeout=10)
  vars = {}

  driver.get(ENDPOINT)
  driver.set_window_size(974, 1032)
  driver.implicitly_wait(3)
  driver.find_element(By.LINK_TEXT, "Sign up").click()
  driver.find_element(By.NAME, "email").click()
  driver.find_element(By.NAME, "email").send_keys("nguyenhungkhang456@gmail.com")
  driver.find_element(By.NAME, "password").click()
  driver.find_element(By.NAME, "password").send_keys("123")
  driver.find_element(By.NAME, "confirm_password").click()
  driver.find_element(By.NAME, "confirm_password").send_keys("1234")
  driver.find_element(By.CSS_SELECTOR, "button").click()
  time.sleep(10.0)
  driver.find_element(By.NAME, "confirm_password").click()

  driver.quit()
