name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install required python modules
        run: |
          python -m pip install --upgrade boto3 moto pytest pytest-github-report pytest-cov coverage pre-commit pytest-html selenium
          pip install pytest-html
          
      - name: Run tests
        run: |
          cd Test
          python -m pytest --html=report.html
        
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: Test/report.html
